### PR TITLE
Allow port numbers in remote

### PR DESCRIPTION
**Pull request by markgdawson**
Allow remotes of the form:

ssh://git@gitlab.some-domain.com:1234/owner/project.git

### CODE REVIEW

**Comment by TxGVNN** [comment]
Hi, thanks for contribute.

I wonder how we can know numbers after `:` is port and not a username (in a path)? Because I see GitHub allows account name is number. 
If we add a new feature, I don't want it to break old works. So we have to cover all cases

**Comment by markgdawson** [comment]
Very good point!

[This is what forge does](https://github.com/magit/forge/blob/master/lisp/forge-core.el#L242)

forge-alist is a list, which in my case contains an entry:
```
("gitlab.mycompany.com" "gitlab.mycompany.com/api/v4" "gitlab.my-company.com" forge-gitlab-repository)
```
as well as other popular forge urls.

This works fine for:
```
(forge--split-url "git@gitlab.mycompany.com:1234/owner/project.git")
(forge--split-url "git@gitlab.mycompany.com:1234/5678/project.git")
(forge--split-url "git@gitlab.mycompany.com:/owner/project.git")
(forge--split-url "git@gitlab.mycompany.com:/1234/project.git")
```
but returns a nil user for:
(forge--split-url "git@gitlab.mycompany.com:1234/project.git")

**Comment by markgdawson** [comment]
Commit above includes an adaptation of the regexp used by forge, and works for the cases above.

Can be tested with:
```
(gitlab-pipeline--url-regexp "git@gitlab.mycompany.com:1234/owner/project.git")
(gitlab-pipeline--url-regexp "git@gitlab.mycompany.com:1234/5678/project.git")
(gitlab-pipeline--url-regexp "git@gitlab.mycompany.com:/owner/project.git")
(gitlab-pipeline--url-regexp "git@gitlab.mycompany.com:/1234/project.git")
```

**Comment by TxGVNN** [comment]
Thank you, A perfect solution!

**Pull request merged**
